### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [rufengsuixing/luci-app-autoipsetadder#1]
这个除了make文件的依赖 还需要其他的依赖吗
master 主库 
![QQ截图20191229215402](https://user-images.githubusercontent.com/26851715/71557777-dde4d580-2a85-11ea-8258-d95d94983c2c.png)

**Comment by rufengsuixing** [comment]
没有了，可能是因为日志不存在导致的错误可以尝试
touch /tmp/addlist.log

**Comment by fuqiang03** [comment]
touch /tmp/addlist.log 手动后不报错了 但是......
![QQ截图20191230215146](https://user-images.githubusercontent.com/26851715/71584693-d3dad980-2b4e-11ea-89d0-6f1748a6cc72.png)

**Comment by rufengsuixing** [comment]
https://github.com/rufengsuixing/luci-app-autoipsetadder/releases/tag/1.0-7

**Comment by fuqiang03** [comment]
已经能正常运行了

**Comment by fuqiang03** [comment]
@rufengsuixing 
我想请教个事,就是
op主库的代码不做任何修改用glibc编译 perl 遇到过错误吗

**Comment by rufengsuixing** [comment]
没用过

**Comment by fuqiang03** [comment]
谢谢了
